// ---------------------------------------------------------------------------
// generateReadme — creates a README.md for prototype export ZIPs.
// ---------------------------------------------------------------------------

import type { BrandConfig } from '../types/brand'

interface ReadmePage {
  route: string
  title: string
  description: string
}

export function generateReadme(
  appName: string,
  pages: ReadmePage[],
  brand: BrandConfig,
): string {
  const now = new Date().toISOString().split('T')[0]

  const routeList = pages
    .map((p) => {
      const file = p.route === '/' ? 'index.html' : `${p.route.replace(/^\//, '')}.html`
      return `| \`${p.route}\` | ${p.title} | ${p.description} | \`pages/${file}\` |`
    })
    .join('\n')

  return `# ${appName}

> Prototype exported from SigAI Workspace on ${now}

## Brand

- **Company:** ${brand.companyName}
- **Primary color:** ${brand.colors.primary}
- **Secondary color:** ${brand.colors.secondary}
- **Font family:** ${brand.typography.fontFamily}
- **Button style:** ${brand.buttonStyle}

## Pages (${pages.length})

| Route | Title | Description | File |
|-------|-------|-------------|------|
${routeList}

## Token Summary

| Token | Value |
|-------|-------|
| Primary | ${brand.colors.primary} |
| Secondary | ${brand.colors.secondary} |
| Background | ${brand.colors.background} |
| Text | ${brand.colors.text} |
| Border | ${brand.colors.border} |
| Font Family | ${brand.typography.fontFamily} |
| Base Size | ${brand.typography.baseSizePx}px |
| Button Radius | ${brand.borderRadius.button} |
| Card Radius | ${brand.borderRadius.card} |
| Input Radius | ${brand.borderRadius.input} |
| Spacing Unit | ${brand.spacing.unit}px |

## Note

This prototype contains static HTML pages with inline styles only.
It is intended for review and stakeholder feedback.
Backend implementation, interactivity, and production deployment are required separately.

---

*Generated by SigAI Prototype Lab*
`
}
